# Permalinks
#
# Use of `relative_permalinks` ensures post links from the index work properly.
permalink:           pretty
relative_permalinks: true


# Setup
title:               Robot Brain Media
tagline:             'A Digital Consulting Agnecy'
description:         'Robot Brain Media helps companies curate, build and explore their digital presence. </br></br> We are not robots.'
url:                 http://www.robotbrain.media
baseurl:             'aleclinehan.github.io'
paginate:            5

# About/contact
author:
  name:              Robot Brain
  url:               https://twitter.com/robotbrainmedia
  email:             hello@robotbrain.media

# Custom vars
version:             1.0.0
